---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/Dropbox/miscelanea/svm-r-markdown-templates/svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Steven C. Gonzalez

jobtitle: "GIS Professional, Knight Federal Solutions"
address: "2457 W Wilson Ave, Chicago, IL 60625"
fontawesome: yes
email: stevenconnorg@gmail.com
# github: stevenconnorg
phone: "(210) 601 - 9549"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Employment

*Knight Federal Solutions*

GIS Professional (San Antonio, TX) \hfill 03/2018 - Present

*Bexar Appraisal District*

Researcher (GIS Technician) \hfill 06/2017 - 03/2018

GIS Intern (San Antonio, TX)\hfill 09/2016 - 01/2017


*University of Texas*

Business Research Assistant (San Antonio, TX) \hfill 01/2017 - 06/2017


*Texas State University*

GIS Research Assistant (San Marcos, TX) \hfill 01/2017 - 01/2018

Researcher (Dublin) \hfill 1899-1935


# Education

*Texas State University*, M.S. Geography \hfill 2018

*Texas State University*, B.s. Geography,  Environmental Studies \hfill 2016

# Awards

*Texas State University's* 2015 - 2016 Award for Academic Excellence (Top 95%)

*Phi Kappa Phi* Honor Society (4.0 GPA)


# References

Available upon request, though likely would include Karl Pearson and Ronald A. Fisher. Please send corrections, feedback, or details of missed publications (of which there are probably a few) to svmille@clemson.edu.
